### ISSUE TITLE
MbtiTest iframe 삽입시, 보안이슈로 'refused to connect' 에러 발생

### ISSUE THREAD

**Issue by danakim530** [Sassy-Project/front-setup#39]
## 📌 Feature Issues

MbtiTest iframe 삽입시, 보안이슈로 'refused to connect' 에러 발생하고 있습니다. 

<img width="797" alt="Screen Shot 2023-04-10 at 22 44 57" src="https://user-images.githubusercontent.com/124070996/230913189-c392d669-1d3a-4160-9d86-8d1b36557e0c.png">

_"iframe은 XSS(cross site scripting)등의 보안 이슈들을 야기할 수 있기 때문에 이를 차단하기 위해서 서비스 공급자 (여기서는 www.16personalities.com )에서 http헤더를 통해 페이지 렌더링 여부 등을 제한할 수 있습니다. 서비스 공급자는 해당 사이트가 iframe에 표시되는 것을 막기 위해 header설정을 통해 페이지의 도메인과 frame의 도메인이 같은지 여부를 확인하도록 하고, 둘이 다르다면 에러를 리턴하도록 한 것입니다"_ 

## ✨ To-do
- [ ] 에러 해결 또는 iframe 대신 사용할 수 있는 기능이 있는지 찾아보겠습니다!

**Comment by 1yoouoo** [comment]
백앤드에서 열어줘야하는데 오늘 여쭤보겠습니다.

**Comment by danakim530** [comment]
✅ iframe 보안 이슈 해결 못함 ->  mbti 테스트 기능 자체 제작하기로 결정
