### ISSUE TITLE
[fix]회원가입 이메일 중복체크시 api 반복 호출

### ISSUE THREAD

**Issue by dongjoonyang** [Sassy-Project/front-setup#74]
## 📌 Feature Issues

이메일 중복체크 api 반복 호출 해결 예정

## ✨ To-do

- [x] api 반복 호출 수정
- [x] debounce 도입
- [x] 이메일 유효성 검사 정규식 수정

**Comment by Eriniss** [comment]
useEffect(() => {
    // 디바운스 적용
    const timer = setTimeout(() => {
      if (!regEmail.test(userEmail)) {
        setIsValidEmail(true);
        setEmailErrorMessage(EMAIL_VALID_CHECK);
      }
    }, 500);

동준님이 작성하신 signUp 컴포넌트에 간단한 디바운스 로직을 추가하여 불필요한 API 호출을 방지하였습니다. 참고하시면 좋을듯 해요.
