### ISSUE TITLE
users/{userId} 동적 할당 및 select value값이 변경 안되는 현상 디버깅

### ISSUE THREAD

**Issue by Eriniss** [Sassy-Project/front-setup#96]
## 📌 Feature Issues
users/:userId로 하드코딩 되어있는 라우팅 처리
LabelBasicSelect 컴포넌트에 value값이 변경되지 않는 현상

## ✨ To-do
- [x] users/{userId} 라우팅 동적 할당. 이를위해 토큰에 있는 id값을 가져와야 합니다.
- [x] LabelBasicSelect 컴포넌트에 value값이 적용되도록 수정합니다.

**Comment by dongjoonyang** [comment]
이슈 처리하였습니다.
